spring:
  profiles:
    group:
      test: "test"
      local: "local"
      dev: "dev, datasource, actuator"
      prod: "prod, datasource, actuator"
    include:
      - redis
      - security
      - s3

spring-doc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    disable-swagger-default-url: true
    path: /swagger-ui
    doc-expansion : none